/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      accentColor: {
        DEFAULT: 'rgb(var(--theme-accent) / <alpha-value>)',
        'theme-focus-ring': 'rgb(var(--theme-focus-ring) / <alpha-value>)',
        'theme-danger': 'rgb(var(--theme-danger) / <alpha-value>)',
      },
      colors: {
        theme: {
          bg: 'rgb(var(--theme-bg) / <alpha-value>)',
          'bg-secondary': 'rgb(var(--theme-bg-secondary) / <alpha-value>)',
          'bg-elevated': 'rgb(var(--theme-bg-elevated) / <alpha-value>)',
          'bg-hover': 'rgb(var(--theme-bg-hover) / <alpha-value>)',
          'bg-active': 'rgb(var(--theme-bg-active) / <alpha-value>)',
          overlay: 'rgb(var(--theme-overlay) / <alpha-value>)',
          'msg-user': 'rgb(var(--theme-msg-user) / <alpha-value>)',
          'msg-ai': 'rgb(var(--theme-msg-ai) / <alpha-value>)',
          'code-bg': 'rgb(var(--theme-code-bg) / <alpha-value>)',
          text: 'rgb(var(--theme-text) / <alpha-value>)',
          'text-secondary': 'rgb(var(--theme-text-secondary) / <alpha-value>)',
          muted: 'rgb(var(--theme-text-muted) / <alpha-value>)',
          subtle: 'rgb(var(--theme-text-subtle) / <alpha-value>)',
          'accent-text': 'rgb(var(--theme-text-accent) / <alpha-value>)',
          'accent-dim': 'rgb(var(--theme-text-accent-dim) / <alpha-value>)',
          'danger-text': 'rgb(var(--theme-text-danger) / <alpha-value>)',
          accent: 'rgb(var(--theme-accent) / <alpha-value>)',
          'accent-hover': 'rgb(var(--theme-accent-hover) / <alpha-value>)',
          danger: 'rgb(var(--theme-danger) / <alpha-value>)',
          'danger-hover': 'rgb(var(--theme-danger-hover) / <alpha-value>)',
          border: 'rgb(var(--theme-border) / <alpha-value>)',
          'border-light': 'rgb(var(--theme-border-light) / <alpha-value>)',
          'icon-user': 'rgb(var(--theme-icon-user) / <alpha-value>)',
          'icon-ai': 'rgb(var(--theme-icon-ai) / <alpha-value>)',
          purple: 'rgb(var(--theme-purple) / <alpha-value>)',
          amber: 'rgb(var(--theme-amber) / <alpha-value>)',
          'icon-muted': 'rgb(var(--theme-icon-muted) / <alpha-value>)',
          'switch-off': 'rgb(var(--theme-switch-off) / <alpha-value>)',
          blue: 'rgb(var(--theme-blue) / <alpha-value>)',
          'blue-text': 'rgb(var(--theme-blue-text) / <alpha-value>)',
          spinner: 'rgb(var(--theme-spinner) / <alpha-value>)',
          'focus-ring': 'rgb(var(--theme-focus-ring) / <alpha-value>)',
          'preview-bg': 'rgb(var(--theme-preview-bg) / <alpha-value>)',
        },
      },
      borderRadius: {
        DEFAULT: 'var(--theme-radius)',
        sm: 'var(--theme-radius-sm)',
        md: 'var(--theme-radius-md)',
        lg: 'var(--theme-radius-lg)',
        xl: 'var(--theme-radius-xl)',
        '2xl': 'var(--theme-radius-2xl)',
        full: 'var(--theme-radius-full)',
      },
      boxShadow: {
        xl: 'var(--theme-shadow-xl)',
        '2xl': 'var(--theme-shadow-2xl)',
      },
      fontFamily: {
        sans: ['var(--theme-font-sans)'],
        mono: ['var(--theme-font-mono)'],
      },
      fontSize: {
        xs: ['var(--theme-text-xs)', { lineHeight: '1rem' }],
        sm: ['var(--theme-text-sm)', { lineHeight: '1.25rem' }],
        base: ['var(--theme-text-base)', { lineHeight: '1.5rem' }],
        lg: ['var(--theme-text-lg)', { lineHeight: '1.75rem' }],
        xl: ['var(--theme-text-xl)', { lineHeight: '1.75rem' }],
        '2xl': ['var(--theme-text-2xl)', { lineHeight: '2rem' }],
      },
      fontWeight: {
        medium: 'var(--theme-font-medium)',
        semibold: 'var(--theme-font-semibold)',
        bold: 'var(--theme-font-bold)',
      },
      transitionDuration: {
        DEFAULT: 'var(--theme-duration)',
      },
      transitionTimingFunction: {
        DEFAULT: 'var(--theme-ease)',
      },
      width: {
        '72': 'var(--theme-sidebar-width)',
        '64': 'var(--theme-dropdown-width)',
      },
      maxWidth: {
        '4xl': 'var(--theme-chat-max-width)',
        '3xl': 'var(--theme-panel-max-width)',
      },
      zIndex: {
        '50': 'var(--theme-z-modal)',
      },
      animation: {
        spin: 'spin var(--theme-spin-duration) linear infinite',
        pulse: 'pulse var(--theme-pulse-duration) cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
    },
  },
  plugins: [],
}
