#!/usr/bin/env node
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(__dirname, '..', '..')
const frontendDir = resolve(__dirname, '..')
const repoEnv = resolve(repoRoot, '.env')
const frontendEnv = resolve(frontendDir, '.env')

function readRepoEnv() {
  if (!existsSync(repoEnv)) return {}
  const out = {}
  for (const raw of readFileSync(repoEnv, 'utf8').split('\n')) {
    const line = raw.trim()
    if (!line || line.startsWith('#')) continue
    const eq = line.indexOf('=')
    if (eq < 0) continue
    const k = line.slice(0, eq).trim()
    let v = line.slice(eq + 1).trim()
    if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) {
      v = v.slice(1, -1)
    }
    out[k] = v
  }
  return out
}

function normalizeBaseUrl(raw) {
  let url = raw.trim()
  while (url.endsWith('/')) url = url.slice(0, -1)
  try {
    const u = new URL(url)
    if (u.protocol !== 'https:' && u.protocol !== 'http:') {
      throw new Error('must be http(s)')
    }
    return `${u.origin}${u.pathname === '/' ? '' : u.pathname}/api`
  } catch (e) {
    throw new Error(`Invalid URL: ${raw}`)
  }
}

function writeFrontendEnv(apiBase) {
  const dir = dirname(frontendEnv)
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
  const body = `# Generated by scripts/prebuild.mjs on ${new Date().toISOString()}\n` +
    `# Do not edit by hand - run \`npm run mobile:prebuild\` to regenerate.\n` +
    `VITE_API_BASE=${apiBase}\n`
  writeFileSync(frontendEnv, body)
}

async function promptForUrl() {
  const { isCancel, text } = await import('@clack/prompts')
  const value = await text({
    message: 'Enter the LLMDash server URL to bake into the mobile app (e.g. https://ai.redforged.eu/):',
    placeholder: 'https://your-llmdash-server.example/',
    validate: (v) => {
      try { normalizeBaseUrl(v || ''); return undefined }
      catch (e) { return e.message }
    },
  })
  if (isCancel(value)) {
    console.error('\nAborted by user.')
    process.exit(130)
  }
  return value
}

async function main() {
  let url = process.env.LLMDASH_SERVER_URL
  if (!url) {
    const fromFile = readRepoEnv().LLMDASH_SERVER_URL
    if (fromFile) url = fromFile
  }

  if (!url) {
    if (process.stdin.isTTY) {
      url = await promptForUrl()
    } else {
      console.error(
        '\n[mobile:prebuild] LLMDASH_SERVER_URL is not set.\n' +
        'Provide it in one of:\n' +
        '  - the .env file at the repo root (LLMDASH_SERVER_URL=...)\n' +
        '  - the LLMDASH_SERVER_URL environment variable\n' +
        'Or run this command interactively in a terminal.\n',
      )
      process.exit(1)
    }
  }

  let apiBase
  try { apiBase = normalizeBaseUrl(url) }
  catch (e) {
    console.error(`[mobile:prebuild] ${e.message}`)
    process.exit(1)
  }

  writeFrontendEnv(apiBase)
  console.log(`[mobile:prebuild] VITE_API_BASE = ${apiBase}`)
}

main().catch((e) => {
  console.error('[mobile:prebuild] unexpected error:', e)
  process.exit(1)
})
